spring:
  application:
    name: micro-news-backend

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/micro-news
    username: mn_backend_user
    password: mn_Backend_Password_2026#
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

app:
  media:
    directory: ${user.home}/micro-news-static

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
